// Package report turns findings into a HackerOne/Bugcrowd-ready markdown document.
// This is the deterministic baseline; the /huntx skill layers LLM triage, semantic
// dedup, and per-program tailoring on top of the same finding set.
package report

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/talkdedsec/tlk-huntx/internal/finding"
)

var order = map[finding.Severity]int{
	finding.Critical: 0, finding.High: 1, finding.Medium: 2, finding.Low: 3, finding.Info: 4,
}

var remediation = map[string]string{
	"exposed-dotenv":        "Remove the .env file from the web root and rotate any exposed credentials.",
	"exposed-git-config":    "Block access to the .git directory at the web server and remove it from production.",
	"directory-listing":     "Disable automatic directory indexing (e.g. `autoindex off` / `Options -Indexes`).",
	"cors-reflected-origin": "Do not reflect arbitrary Origins; allow-list trusted origins and avoid credentials with wildcard.",
	"missing-hsts":          "Send Strict-Transport-Security with an adequate max-age over HTTPS.",
	"bola-differential":     "Enforce per-object authorization server-side; check that the caller owns the requested object.",
}

func Markdown(program string, findings []finding.Finding) string {
	fs := append([]finding.Finding(nil), findings...)
	sort.SliceStable(fs, func(i, j int) bool {
		if order[fs[i].Severity] != order[fs[j].Severity] {
			return order[fs[i].Severity] < order[fs[j].Severity]
		}
		return fs[i].TemplateID < fs[j].TemplateID
	})

	var b strings.Builder
	title := program
	if title == "" {
		title = "target"
	}
	fmt.Fprintf(&b, "# Security findings — %s\n\n", title)
	fmt.Fprintf(&b, "_Generated by huntx on %s._\n\n", time.Now().UTC().Format("2006-01-02"))

	counts := map[finding.Severity]int{}
	verified := 0
	for _, f := range fs {
		counts[f.Severity]++
		if f.Verified {
			verified++
		}
	}
	fmt.Fprintf(&b, "%d finding(s), %d deterministically verified.\n\n", len(fs), verified)
	b.WriteString("| Severity | Count |\n|---|---|\n")
	for _, s := range []finding.Severity{finding.Critical, finding.High, finding.Medium, finding.Low, finding.Info} {
		if counts[s] > 0 {
			fmt.Fprintf(&b, "| %s | %d |\n", s, counts[s])
		}
	}
	b.WriteString("\n---\n\n")

	for i, f := range fs {
		name := f.Type
		if name == "" {
			name = f.TemplateID
		}
		fmt.Fprintf(&b, "## %d. %s\n\n", i+1, name)
		sev := string(f.Severity)
		if sev == "" {
			sev = "info"
		}
		fmt.Fprintf(&b, "- **Severity:** %s", sev)
		if f.CVSS != "" {
			fmt.Fprintf(&b, " (CVSS %s)", f.CVSS)
		}
		b.WriteString("\n")
		if f.CWE != "" {
			fmt.Fprintf(&b, "- **Weakness:** %s\n", f.CWE)
		}
		fmt.Fprintf(&b, "- **Confidence:** %d%%\n", f.Confidence)
		fmt.Fprintf(&b, "- **Verified:** %v\n", f.Verified)
		fmt.Fprintf(&b, "- **URL:** %s\n\n", f.MatchedAt)

		if f.Evidence.Request != "" || f.Evidence.Response != "" {
			b.WriteString("### Evidence\n\n```\n")
			if f.Evidence.Request != "" {
				b.WriteString(f.Evidence.Request + "\n\n")
			}
			if f.Evidence.Response != "" {
				b.WriteString(f.Evidence.Response + "\n")
			}
			if f.Evidence.OOBProof != "" {
				b.WriteString("\nOOB: " + f.Evidence.OOBProof + "\n")
			}
			b.WriteString("```\n\n")
		}
		if f.Repro != "" {
			fmt.Fprintf(&b, "### Reproduction\n\n```\n%s\n```\n\n", f.Repro)
		}
		if r := remediationFor(f.TemplateID); r != "" {
			fmt.Fprintf(&b, "### Remediation\n\n%s\n\n", r)
		}
		b.WriteString("---\n\n")
	}
	return b.String()
}

func remediationFor(templateID string) string {
	if r, ok := remediation[templateID]; ok {
		return r
	}
	if strings.HasPrefix(templateID, "secret-") {
		return "Revoke and rotate the exposed secret immediately, then remove it from the served asset and history."
	}
	return ""
}
